## <center>  Data Science Essentials (CIA2C14) </center>
### <center>  Practical 2 : Acquire and Identify Data with panda </center>

A DataFrame is a powerful way to manage your data in a tabular format. You work with rows and columns—much like a spreadsheet—and it provides a structured way to store, analyze, and model your data. Here’s why you find it so useful: <br>

Organized Structure: <br>
You can easily view, manipulate, and analyze your data because everything is neatly arranged in rows and columns. <br>

Easy Data Manipulation:<br>
It allows you to sort, filter, and transform data with straightforward functions, making your analysis efficient. <br>

Essential for Modeling:<br>
Most modeling tools and libraries expect data in a DataFrame format. This means you use it as a common starting point for building models, running algorithms, and testing hypotheses.<br>

Integrated with Libraries:<br>
You can integrate DataFrames with tools like pandas (for Python), which streamlines data cleaning, statistical operations, and even visualizations for better insight.<br>

Understanding DataFrames is key to any data-related task, especially modeling, as they provide a consistent and flexible format to work with data effectively.

# 1.0 Pandas DF: Using pd to read csv to create DF

In [2]:
import pandas as pd
from io import StringIO

# Create a CSV string with the specific values on separate rows.
csv_data = """A
1,0
2,NA
3,null
4,None
5,
6,nil"""

# Read the CSV data.
df = pd.read_csv(StringIO(csv_data))

# Display the DataFrame.
print(df)

# Check the type of each cell in column A.
for index, value in df['A'].items():
    print(f"Row {index}: Value = {value}, Type = {type(value)}")

     A
1    0
2  NaN
3  NaN
4  NaN
5  NaN
6  nil
Row 1: Value = 0, Type = <class 'str'>
Row 2: Value = nan, Type = <class 'float'>
Row 3: Value = nan, Type = <class 'float'>
Row 4: Value = nan, Type = <class 'float'>
Row 5: Value = nan, Type = <class 'float'>
Row 6: Value = nil, Type = <class 'str'>

In [3]:
import pandas as pd
import numpy as np

list1 = [0, 'NA', 'null', None,np.nan, 'nil']
list1_df = pd.DataFrame(list1, columns=['A'])
print(list1_df)

for index, value in list1_df['A'].items():
    print(f"Row {index}: Value = {value}, Type = {type(value)}")

      A
0     0
1    NA
2  null
3  None
4   NaN
5   nil
Row 0: Value = 0, Type = <class 'int'>
Row 1: Value = NA, Type = <class 'str'>
Row 2: Value = null, Type = <class 'str'>
Row 3: Value = None, Type = <class 'NoneType'>
Row 4: Value = nan, Type = <class 'float'>
Row 5: Value = nil, Type = <class 'str'>

In [4]:
#print current pandas version
pd.__version__

'2.2.2'

# 1.1 Pandas DF: Using lists to create DF

In [5]:
#Create a nested list
my_list = [[1,2.0,3,'NA'],[1,2,3],[1,1],[1,1,2,2],[2,0,0,]] #note that not all lists contain same no. of ele
my_list

[[1, 2.0, 3, 'NA'], [1, 2, 3], [1, 1], [1, 1, 2, 2], [2, 0, 0]]

In [6]:
#To create a DataFrame from an array (nested list)
import pandas as pd
my_list_df=pd.DataFrame(my_list)
my_list_df

   0    1    2     3
0  1  2.0  3.0    NA
1  1  2.0  3.0  None
2  1  1.0  NaN  None
3  1  1.0  2.0     2
4  2  0.0  0.0  None

In [7]:
#name columns
my_list_df.columns=['col1','col2','col3','col4']
my_list_df

   col1  col2  col3  col4
0     1   2.0   3.0    NA
1     1   2.0   3.0  None
2     1   1.0   NaN  None
3     1   1.0   2.0     2
4     2   0.0   0.0  None

Qn: What did you observe? <br><br>
Ans: NA, NaN and None are observed. NA is created intentionally, NaN and None was not mentioned in the list.

In [8]:
#lets determine the dtypes of columns and location of specific values first
my_list_df.dtypes

col1      int64
col2    float64
col3    float64
col4     object
dtype: object

<font color=red> tutor to highlight this step as important, dtypes affects processes downstream in the pipeline (data prep, modelling, etc). hint to students, encoding. </font>

Note: now the dtypes' rows are describing the columns of the df.

In [9]:
my_list_df.iloc[2,2]

np.float64(nan)

Qn: for .iloc[2,2] , what does the coordinate refer to? Is it .iloc[row,column] or .iloc[column,row] ?

In [10]:
my_list_df.iloc[3,]

col1      1
col2    1.0
col3    2.0
col4      2
Name: 3, dtype: object

In [11]:
my_list_df.iloc[3,:]

col1      1
col2    1.0
col3    2.0
col4      2
Name: 3, dtype: object

In [12]:
my_list_df.iloc[,3]

SyntaxError: invalid syntax (<ipython-input-12-82ce3f7b02d0>, line 1)

In [13]:
my_list_df.iloc[:,3]

0      NA
1    None
2    None
3       2
4    None
Name: col4, dtype: object

Qn: What did you observe? <br><br>
Ans:  .iloc uses .loc[row,column]. it is better to use : if you want all of row or column, to avoid error.

In [14]:
(my_list_df.iloc[1,3]) #why is there 'no' output?

In [15]:
type(my_list_df.iloc[1,3])

NoneType

Qn: In summary, What did you observe? <br><br>
Ans: when one of the value in the column is a string, all values will be defined as object. missing value will be NoneType. if values are all numerical integer, the column will be int64. if one of the value is float, the column will be float64. for numerical column with missing value, it will be defined as float64, because missing value is a float64 type by default.

#1.2 Describe your DF

In [16]:
#loop through all column to print values.mean
for i in range(len(my_list_df.columns)):
    print(my_list_df.iloc[:,i].mean())

1.2
1.2
2.0

TypeError: can only concatenate str (not "int") to str

cannot apply mean to categorical column

In [17]:
my_list_df.describe()

           col1     col2      col3
count  5.000000  5.00000  4.000000
mean   1.200000  1.20000  2.000000
std    0.447214  0.83666  1.414214
min    1.000000  0.00000  0.000000
25%    1.000000  1.00000  1.500000
50%    1.000000  1.00000  2.500000
75%    1.000000  2.00000  3.000000
max    2.000000  2.00000  3.000000

in a normal .describe() catgeorical column do not show up

In [18]:
for i in range(len(my_list_df.columns)):
    print(my_list_df.iloc[:,i].describe())

count    5.000000
mean     1.200000
std      0.447214
min      1.000000
25%      1.000000
50%      1.000000
75%      1.000000
max      2.000000
Name: col1, dtype: float64
count    5.00000
mean     1.20000
std      0.83666
min      0.00000
25%      1.00000
50%      1.00000
75%      2.00000
max      2.00000
Name: col2, dtype: float64
count    4.000000
mean     2.000000
std      1.414214
min      0.000000
25%      1.500000
50%      2.500000
75%      3.000000
max      3.000000
Name: col3, dtype: float64
count      2
unique     2
top       NA
freq       1
Name: col4, dtype: object

.describe() does work on categeroical column when requested to do.

What is the difference between two observations above? <br><br>

.describe() over multiple columns will only do so for numerical columns. to .describe() categorical column, apply only to categorical column. a way to work around is to use 'include='all')

In [19]:
my_list_df.describe(include='all')

            col1     col2      col3 col4
count   5.000000  5.00000  4.000000    2
unique       NaN      NaN       NaN    2
top          NaN      NaN       NaN   NA
freq         NaN      NaN       NaN    1
mean    1.200000  1.20000  2.000000  NaN
std     0.447214  0.83666  1.414214  NaN
min     1.000000  0.00000  0.000000  NaN
25%     1.000000  1.00000  1.500000  NaN
50%     1.000000  1.00000  2.500000  NaN
75%     1.000000  2.00000  3.000000  NaN
max     2.000000  2.00000  3.000000  NaN

<font color=red> tutor to highlight this step as important, important step for treatment for outliers, normalisation. tutor to recap what does each column mean.</font>

In [20]:
#print sum of null values per column
(my_list_df.isnull().sum())

col1    0
col2    0
col3    1
col4    3
dtype: int64

In [21]:
#lets try another dataset
import pandas as pd

last_names = ['Connor', 'Connor', 'Reese', 'Doe', 'Doe','Doe','Doey']
first_names = ['Sarah', 'John', 'Kyle', 'John','John','Jack', 'Jill']
age = [23,25,21,20,19,20,20]
df = pd.DataFrame({
  'first_name': first_names,
  'last_name': last_names,
  'age': age
})
df

  first_name last_name  age
0      Sarah    Connor   23
1       John    Connor   25
2       Kyle     Reese   21
3       John       Doe   20
4       John       Doe   19
5       Jack       Doe   20
6       Jill      Doey   20

In [22]:
#print unique values
print(df['first_name'].unique())
print(df['last_name'].unique())

['Sarah' 'John' 'Kyle' 'Jack' 'Jill']
['Connor' 'Reese' 'Doe' 'Doey']

In [23]:
#print count per unique value
print(df['first_name'].value_counts())
print(df['last_name'].value_counts())

first_name
John     3
Sarah    1
Kyle     1
Jack     1
Jill     1
Name: count, dtype: int64
last_name
Doe       3
Connor    2
Reese     1
Doey      1
Name: count, dtype: int64

In [24]:
#lets point to rows with John
(df['first_name']=='John')

0    False
1     True
2    False
3     True
4     True
5    False
6    False
Name: first_name, dtype: bool

In [25]:
#average age and count by first_name
df.groupby('first_name')['age'].agg(['mean','count'])

                 mean  count
first_name
Jack        20.000000      1
Jill        20.000000      1
John        21.333333      3
Kyle        21.000000      1
Sarah       23.000000      1

In [26]:
#lets point to rows with John
df[df['first_name']=='John']

  first_name last_name  age
1       John    Connor   25
3       John       Doe   20
4       John       Doe   19

In [27]:
#lets point to rows with Doe
df[df['last_name']=='Doe']

  first_name last_name  age
3       John       Doe   20
4       John       Doe   19
5       Jack       Doe   20

In [28]:
df[df['age']>=20]

  first_name last_name  age
0      Sarah    Connor   23
1       John    Connor   25
2       Kyle     Reese   21
3       John       Doe   20
5       Jack       Doe   20
6       Jill      Doey   20

In [29]:
df[df['age']!=20]

  first_name last_name  age
0      Sarah    Connor   23
1       John    Connor   25
2       Kyle     Reese   21
4       John       Doe   19

<font color=red> tutor to highlight this step as important, building understanding towards EDA. </font>